[package]
name = "VerifySignature"
version = "0.0.0"

[addresses]
VerifySigAddr = "_"

[dependencies]
AptosFramework = { local = "./sdk/aptos-framework" }
AptosStdlib = { local = "./sdk/aptos-stdlib" }